### ISSUE TITLE
Please update performance results

### ISSUE THREAD

**Issue by stgolem** [mbdavid/LiteDB-Perf#1]
After 3 years of improvements i think we have different results for SQLite and LiteDB.

Please update Readme here with todate benchmark results.

**Comment by emrahbabayigit** [comment]
Add a test for sqlite with this settings:  Journal Mode=WAL;Synchronous=NORMAL

**Comment by mbdavid** [comment]
Hi guys, we are adding new benchmarks in LiteDB repo.
